2024-03-09 22:28:52,170 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Configure stats pid to 15271
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Loading settings from /Users/sunayana/.config/wandb/settings
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Loading settings from /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/settings
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-09 22:28:52,172 INFO    MainThread:15271 [wandb_init.py:_log_setup():526] Logging user logs to /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/offline-run-20240309_222852-ccz542g5/logs/debug.log
2024-03-09 22:28:52,173 INFO    MainThread:15271 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/offline-run-20240309_222852-ccz542g5/logs/debug-internal.log
2024-03-09 22:28:52,173 INFO    MainThread:15271 [wandb_init.py:init():566] calling init triggers
2024-03-09 22:28:52,173 INFO    MainThread:15271 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-09 22:28:52,173 INFO    MainThread:15271 [wandb_init.py:init():616] starting backend
2024-03-09 22:28:52,173 INFO    MainThread:15271 [wandb_init.py:init():620] setting up manager
2024-03-09 22:28:52,176 INFO    MainThread:15271 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-03-09 22:28:52,176 INFO    MainThread:15271 [wandb_init.py:init():628] backend started and connected
2024-03-09 22:28:52,184 INFO    MainThread:15271 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-09 22:28:52,185 INFO    MainThread:15271 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-09 22:28:52,185 INFO    MainThread:15271 [wandb_init.py:init():720] updated telemetry
2024-03-09 22:28:52,212 INFO    MainThread:15271 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-09 22:30:22,590 ERROR   MainThread:15271 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-09 22:30:22,767 ERROR   MainThread:15271 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/sunayana/anaconda3/envs/newenvt/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/sunayana/anaconda3/envs/newenvt/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
